Stop polling in base authenticator view
okta/okta-signin-widget pull request #1642
Opened 2021-02-03 23:43 UTC by pradeepdewda-okta

## Description:
Since we changed idx response status code from 200 to 401 for errors. We are seeing Rate Limit hitting for authenticator views where magic link is involved.

Server responds with 401, but widget don't stop polling and keeps adding a new startPolling timeout that causes a flurry of server calls which increase exponentially.

Removed the generic listener on model errors
If stateToken is invalid or expired then stop polling
continue polling if there is form error but session is still valid
Similar issue: OKTA-365525

## PR Checklist

- [ ] Have you verified the basic functionality for this change?

- [ ] Added unit tests?

- [ ] Added e2e tests

- [ ] Did you follow our [Security Best Practices](https://oktawiki.atlassian.net/wiki/display/eng/Security+Best+practices)?

### Screenshot/Video:
https://okta.box.com/s/jrnfe1sc2xb968o7a5r95347al1luw6o
https://okta.box.com/s/xtw4pozzyu1bpys3ebxs8zm27b1fu3d8

### Reviewers:

### Issue:

- [OKTA-366306](https://oktainc.atlassian.net/browse/OKTA-366306)
- [OKTA-365525](https://oktainc.atlassian.net/browse/OKTA-365525)

2021-02-03 23:50 UTC, magizh-okta requested changes
This doesnt seem right. You need to base ur fix of 5.2.1 but you have based it on 5.2.3

2021-02-03 23:54 UTC, aarongranick-okta approved these changes

2021-02-04 00:18 UTC, haishengwu-okta approved these changes

2021-02-04 01:50 UTC, magizh-okta approved these changes

2021-02-04 18:48 UTC, closed without merging