feat: Adds feature to set default country code on SMS&Call enrolment
okta/okta-signin-widget pull request #1756
Opened 2021-03-18 16:14 UTC by shuowu

## Description:

Converted from #1694 

## PR Checklist

- [ ] Have you verified the basic functionality for this change?

- [ ] Added unit tests?

- [ ] Added e2e tests

- [ ] Did you follow our [Security Best Practices](https://oktawiki.atlassian.net/wiki/display/eng/Security+Best+practices)?

### Screenshot/Video:

### Reviewers:

### Issue:

- [OKTA-373007](https://oktainc.atlassian.net/browse/OKTA-373007)

2021-03-22 16:34 UTC, aarongranick-okta requested changes
Should add description of this option to the README?

2021-03-23 20:31 UTC, shuowu commented on src/EnrollCallAndSmsController.js
> +        countryCode: ['string', false, this.options.appState.get('userCountryCode')],
Wrap the model as a function, here is the only change added.

2021-03-24 17:08 UTC, aarongranick-okta commented on README.md
> +- **defaultCountryCode:** Set the default countryCode of the widget. If no `defaultCountryCode` is provided, defaults to `US`.
Can we clarify this is related to a phone number?

2021-03-24 17:09 UTC, aarongranick-okta approved these changes
minor comment about README

2021-03-24 18:16 UTC, closed without merging