Backport 5.5.1
okta/okta-signin-widget pull request #1804
Opened 2021-04-01 23:19 UTC by haishengwu-okta

## Description:

## PR Checklist

- [ ] Have you verified the basic functionality for this change?

- [ ] Added unit tests?

- [ ] Added e2e tests

- [ ] Did you follow our [Security Best Practices](https://oktawiki.atlassian.net/wiki/display/eng/Security+Best+practices)?

### Screenshot/Video:

### Reviewers:

### Issue:

- [OKTA-XXXXXX](https://oktainc.atlassian.net/browse/OKTA-XXXXXX)

2021-04-01 23:31 UTC, sherizada-okta approved these changes

2021-04-01 23:50 UTC, nikhilvenkatraman-okta approved these changes

2021-04-01 23:52 UTC, anipendakur-okta requested changes
@haishengwu-okta - I don't see my changes.

2021-04-02 00:55 UTC, haishengwu-okta commented
@anipendakur-okta is `Email magiclink takeover` your change?

2021-04-02 01:02 UTC, anipendakur-okta commented
> @anipendakur-okta is `Email magiclink takeover` your change?

Yes, that's the one - https://github.com/okta/okta-signin-widget/pull/1791/files

2021-04-02 05:39 UTC, anipendakur-okta approved these changes

2021-04-02 19:21 UTC, closed without merging