chore: add a note on IdP Discovery feature limitation
okta/okta-signin-widget pull request #1852
Opened 2021-04-19 08:33 UTC by oleksandrpravosudko-okta

## Description:
Add a workaround snippet for IdP discovery with self-hosted widget.

## PR Checklist

- [x] Have you verified the basic functionality for this change?

- [ ] Added unit tests?

- [ ] Added e2e tests

- [ ] Did you follow our [Security Best Practices](https://oktawiki.atlassian.net/wiki/display/eng/Security+Best+practices)?

### Screenshot/Video:

### Reviewers:

### Issue:

- [OKTA-354752](https://oktainc.atlassian.net/browse/OKTA-354752)

2021-04-20 15:58 UTC, oleksandrpravosudko-okta commented on README.md
> +**Note:** v1 API (pre OIE) supports IdP Discovery in Okta-hosted Widget setup only. IdP discovery for self-hosted Widget is not officialy supported by v1 API and requires a workaround to function. Th
it looks like OIE is getting some exposure through the developer [docs](https://developer.okta.com/docs/concepts/ie-intro) although I'm not sure how familiar are users with the term - removing OIE mention

2021-04-23 16:32 UTC, aarongranick-okta requested changes
Looks pretty good. Could you also add some text warning/explaining that this "workaround" requires 3rd-party cookies since it uses these methods:
- session.exists
- token.getWithoutPrompt

2021-04-26 15:05 UTC, shuowu-okta approved these changes

2021-04-26 15:39 UTC, aarongranick-okta approved these changes

2021-04-26 18:07 UTC, closed without merging