Change OIE session expiration message
okta/okta-signin-widget pull request #2004
Opened 2021-06-01 20:22 UTC by ethanhsiung-okta

Resolves: OKTA-394634

## Description:

- Change session expiration message from `The session has expired.` to `The session has expired. Refresh the page and try again.`

## PR Checklist

- [x] Have you verified the basic functionality for this change?

- [x] Added unit tests?

- [ ] Added e2e tests

- [ ] Did you follow our [Security Best Practices](https://oktawiki.atlassian.net/wiki/display/eng/Security+Best+practices)?

### Screenshot/Video:
Before:
![Screen Shot 2021-05-18 at 3 31 30 PM](https://user-images.githubusercontent.com/40326160/120385435-491a8300-c2dc-11eb-8ac4-48b3d8eebaab.png)

After:
![Screen Shot 2021-05-25 at 4 33 44 PM](https://user-images.githubusercontent.com/40326160/120385451-4e77cd80-c2dc-11eb-8b70-4c0b920a0ebb.png)

### Reviewers:

- @rameshbhojan-okta @anipendakur-okta 

### Issue:

- [OKTA-394634](https://oktainc.atlassian.net/browse/OKTA-394634)

2021-06-01 20:31 UTC, vincentvoong-okta reviewed
LGTM

2021-06-01 20:42 UTC, rameshbhojan-okta commented
> LGTM

@vincentvoong-okta - Did we intentionally make a choice to not use fillers like `Please` etc.? e.g. `Please refresh the page...`?

2021-06-01 20:43 UTC, rameshbhojan-okta approved these changes

2021-06-01 21:13 UTC, pradeepdewda-okta commented
How to make sure that the action `Refresh the page and try again` will always work for all the flows ?

2021-06-01 21:15 UTC, pradeepdewda-okta requested changes
I am working on this ticket https://oktainc.atlassian.net/browse/OKTA-392835 that adds `Back to sign in` link which basically does a page refresh and clears any locally stored stateToken.. I feel that should be the right solution.

2021-06-01 21:23 UTC, ethanhsiung-okta commented
> I am working on this ticket https://oktainc.atlassian.net/browse/OKTA-392835 that adds `Back to sign in` link which basically does a page refresh and clears any locally stored stateToken.. I feel that should be the right solution.

@pradeepdewda-okta I agree, this makes more sense. @vincentvoong-okta @rameshbhojan-okta thoughts?

2021-06-01 21:42 UTC, rameshbhojan-okta commented
> > I am working on this ticket https://oktainc.atlassian.net/browse/OKTA-392835 that adds `Back to sign in` link which basically does a page refresh and clears any locally stored stateToken.. I feel that should be the right solution.
> 
> @pradeepdewda-okta I agree, this makes more sense. @vincentvoong-okta @rameshbhojan-okta thoughts?

Ok, so then @pradeepdewda-okta - Are we saying we will never throw the Session Expired? I understand your fix would take care of the primary issue reported in the bug - but this PR which fixes the error message was for general scenarios to improve the message with feedback for user when the session indeed expires. (e.g. even from API calls' perspective and not just our SIW UI).

2021-06-01 21:51 UTC, pradeepdewda-okta commented
@rameshbhojan-okta User will still see the error message, as they used to see in `v1` but they can also take action to go back to sign in page once we add `Back to sign in` link to all terminal states. @unniravindranathan-okta

2021-06-03 00:35 UTC, vincentvoong-okta commented
@ethanhsiung-okta @pradeepdewda-okta 
I didn't realize we're also adding `Back to sign in` on this page. At least from the UX side, that would solve the problem of just dead-ending the user.

@rameshbhojan-okta 
Yes, removing "Please" was intentional - generally speaking, we want to use please as little as possible in our language unless we're asking the user to do something fairly inconvenient like waiting for something to download.

2021-06-03 15:48 UTC, rameshbhojan-okta commented
> @rameshbhojan-okta User will still see the error message, as they used to see in `v1` but they can also take action to go back to sign in page once we add `Back to sign in` link to all terminal states. @unniravindranathan-okta

Ok sounds good, @pradeepdewda-okta . So, because of the reasoning above and for the benefit of the API consumers - I think it is still good to get this error message fix in? I am trying to understand if you still need to block this PR or can you go ahead and remove the change request from the PR? 😄

2021-06-03 16:06 UTC, pradeepdewda-okta commented
> > @rameshbhojan-okta User will still see the error message, as they used to see in `v1` but they can also take action to go back to sign in page once we add `Back to sign in` link to all terminal states. @unniravindranathan-okta
> 
> Ok sounds good, @pradeepdewda-okta . So, because of the reasoning above and for the benefit of the API consumers - I think it is still good to get this error message fix in? I am trying to understand if you still need to block this PR or can you go ahead and remove the change request from the PR? 😄

@rameshbhojan-okta just wanted to understand how it will benefit API consumers ? this PR doesn't change API response.. 
Here is my PR that covers generalized use cases for terminal states. https://github.com/okta/okta-signin-widget/pull/1989

2021-06-03 17:18 UTC, ethanhsiung-okta commented
Chatted offline with @rameshbhojan-okta and @pradeepdewda-okta about this.
Pradeep's changes here https://github.com/okta/okta-signin-widget/pull/1989 would add a `Back to sign in`, so we no longer think this change (or any text change) is necessary

2021-06-03 17:18 UTC, closed without merging

2021-06-03 18:28 UTC, rameshbhojan-okta commented
> @rameshbhojan-okta just wanted to understand how it will benefit API consumers ? 

@pradeepdewda-okta - Yes, this doesn't change the API response/attributes as such but it does affect the value of the error message being returned by the API right, which is what our UI currently reads and displays? 
So, where I was getting at was e.g. CIAM customers that may want to consume APIs directly (or through our SDKs), the error messages often provide feedback for them to decide on the next step of action(s).

But, overall - that was just my general comment and not very specific to this change/PR - as I don't feel very strongly about the error message as we can leave it as-is like we discussed offline on slack.