Increasing poll timeout to 5min
okta/okta-signin-widget pull request #2139
Opened 2021-08-09 17:29 UTC by vakaevich-okta

## Description:

Increasing poll timeout to 5min.
Original PR with the discussion: https://github.com/okta/okta-signin-widget/pull/2115

## PR Checklist

- [x] Have you verified the basic functionality for this change?

- [ ] Added unit tests?

- [ ] Added e2e tests

- [ ] Did you follow our [Security Best Practices](https://oktawiki.atlassian.net/wiki/display/eng/Security+Best+practices)?

### Reviewers:

@santoshmale-okta , @johannesstockmann-okta , @diptishiralkar-okta , @arunthotta-okta , @saurinpandya-okta

### Issue:

- [OKTA-406443](https://oktainc.atlassian.net/browse/OKTA-406443)

2021-08-10 21:05 UTC, santoshmale-okta approved these changes

2021-08-10 22:08 UTC, aarongranick-okta requested changes
Please rebase against (and set PR to merge to) `master`.

2021-08-13 08:04 UTC, vakaevich-okta commented
@aarongranick-okta , done: https://github.com/okta/okta-signin-widget/pull/2155

2021-08-19 15:49 UTC, aarongranick-okta commented
was merged: https://github.com/okta/okta-signin-widget/pull/2155

2021-08-19 15:49 UTC, closed without merging