Fix username/password required custom error text for OIE
okta/okta-signin-widget pull request #2233
Opened 2021-10-01 22:52 UTC by denysoblohin-okta

## Description:

Current issue : i18n keys `error.username.required` and `error.password.required` are not applied for v2 (OIE)

## PR Checklist

- [x] Have you verified the basic functionality for this change?

- [x] Added unit tests?

- [ ] Added e2e tests

- [ ] Did you follow our [Security Best Practices](https://oktawiki.atlassian.net/wiki/display/eng/Security+Best+practices)?

### Screenshot/Video:

### Reviewers:

### Issue:

- [OKTA-429891](https://oktainc.atlassian.net/browse/OKTA-429891)

2021-10-12 17:00 UTC, pradeepdewda-okta commented on src/v2/view-builder/internals/BaseModel.js
> +  if (remediationName === 'identify') {
base model should not be aware of form names..

2021-10-12 17:02 UTC, pradeepdewda-okta requested changes
We should not include form name specific code to BaseModel..

2021-10-29 23:18 UTC, denysoblohin-okta commented on test/unit/spec/v2/view-builder/views/IdentifierView_spec.js
> +    testContext.view.form.__save();
Replaced with `testContext.view.form.isValid()`

2021-10-29 23:25 UTC, denysoblohin-okta commented on test/testcafe/spec/Identify_spec.js
> +test.requestHooks(identifyRequestLogger, identifyMock)('should be able to submit identifier if error text for password is customized', async t => {
This test protects from a possible mistake in `validate` function (as in this [snippet](https://github.com/okta/okta-signin-widget/pull/2233#issuecomment-953333352)):
If there is no password value, and it's not needed (no remediation for credentials, only for identifier), validation should pass successfully without adding error to password field.

2021-10-29 23:31 UTC, pradeepdewda-okta commented on test/testcafe/spec/Identify_spec.js
> +test.requestHooks(identifyRequestLogger, identifyMock)('should be able to submit identifier if error text for password is customized', async t => {
update the test name to `should not show custom error if password doesn't exist in remediation`

2021-10-29 23:32 UTC, pradeepdewda-okta approved these changes
Looks good now. ready to go. 🚢

2021-10-30 00:08 UTC, closed without merging