OKTA-442867 Enable multi-row Error to make errors look in multiple line
okta/okta-signin-widget pull request #2336
Opened 2021-12-22 18:45 UTC by abhignanamihirkandepu-okta

## Description:
Update SIW form error message to make it more clear

## PR Checklist

- [ ] Have you verified the basic functionality for this change?

- [ ] Added unit tests?

- [ ] Added e2e tests

- [ ] Did you follow our [Security Best Practices](https://oktawiki.atlassian.net/wiki/display/eng/Security+Best+practices)?

### Screenshot/Video:

### Reviewers:
@okta/ciamx 
@okta/eng-uicore 
@jakebacher2-okta 

### Issue:

- [OKTA-442867](https://oktainc.atlassian.net/browse/OKTA-442867)

2021-12-22 19:17 UTC, haishengwu-okta commented on src/v2/view-builder/internals/BaseForm.js
> +      input["multirowError"] = true;
Probably better to go here: https://github.com/okta/okta-signin-widget/blob/master/src/v2/ion/uiSchemaTransformer.js#L62

2021-12-22 20:35 UTC, abhignanamihirkandepu-okta commented on src/v2/ion/uiSchemaTransformer.js
> +      'multirowError': true,
https://okta.box.com/s/d3us4gwdzc81bnfy9uuabgwcdomfkpn6
here is how the final output looks like, the error messages in this picture will be updated to the new messages below

2022-01-04 17:46 UTC, jakebacher2-okta commented
@justinabrokwah-okta keep me honest here, should this be merged into master or a version branch?

2022-01-04 18:13 UTC, justinabrokwah-okta commented
> @justinabrokwah-okta keep me honest here, should this be merged into master or a version branch?

@jakebacher2-okta is this a bug fix? if so, you'll want to target the weekly release branch (can check #eng-sign-in-widget on slack for the name of the branch). If the change doesn't need to go out ASAP, merging to master here is fine

2022-01-04 18:17 UTC, jakebacher2-okta commented
> 

Not a bugfix so this should be fine, thanks for the insight :)

2022-01-06 13:56 UTC, jakebacher2-okta approved these changes

2022-01-06 18:10 UTC, pradeepdewda-okta commented
@abhignanamihirkandepu-okta explain accurately what your PR or fix does in PR description. It's better instead of generalizing statements.

2022-01-06 18:11 UTC, pradeepdewda-okta requested changes
Add unit tests and testcafe tests

2022-01-07 22:52 UTC, pradeepdewda-okta approved these changes

2022-01-12 03:09 UTC, closed without merging