fix: clears otp from settings on restartLoginFlow
okta/okta-signin-widget pull request #2513
Opened 2022-05-11 20:57 UTC by jaredperreault-okta

## Description:
fixes issue where widget is loaded via email magic link, then browser window is refreshed displayed an otp error.

## PR Checklist

- [ ] Have you verified the basic functionality for this change?

- [ ] Added unit tests?

- [ ] Added e2e tests

- [ ] Did you follow our [Security Best Practices](https://oktawiki.atlassian.net/wiki/display/eng/Security+Best+practices)?

- Did you verify the change by running downstream monolith artifacts? (YES | NO | UNSURE)

### Screenshot/Video:

### Reviewers:

### Issue:

- [OKTA-495883](https://oktainc.atlassian.net/browse/OKTA-495883)

2022-05-11 21:05 UTC, aarongranick-okta approved these changes

2022-05-13 18:08 UTC, justinabrokwah-okta reviewed
Changes look good! - if possible can you provide a video to verify the fix?

2022-05-13 18:39 UTC, lokeshhemrajani-okta commented on src/v2/view-builder/views/consent/EmailMagicLinkOTPTerminalView.js
> +  enterCodeOnFlowPage = challengeIntent
can you add test for this?

2022-05-13 18:39 UTC, lokeshhemrajani-okta requested changes

2022-05-13 18:39 UTC, lokeshhemrajani-okta commented on src/v2/view-builder/views/consent/EmailMagicLinkOTPTerminalView.js
> +  enterCodeOnFlowPage = challengeIntent
can you add test for this?

2022-05-18 18:41 UTC, jaredperreault-okta commented on src/v2/view-builder/views/consent/EmailMagicLinkOTPTerminalView.js
> +  enterCodeOnFlowPage = challengeIntent
added

2022-05-18 18:44 UTC, jaredperreault-okta commented
@justinabrokwah-okta videos added

2022-05-18 20:39 UTC, justinabrokwah-okta approved these changes
LGTM, thanks for the quick fix!

2022-05-20 14:11 UTC, closed without merging