OKTA-521071 rebase post-release commits
okta/okta-signin-widget pull request #2669
Opened 2022-08-04 00:09 UTC by lesterchoi-okta

## Description:

Pull in post-release commits excluding package.json version "revving up"

## PR Checklist

- [ ] Have you verified the basic functionality for this change?

- [ ] Added unit tests?

- [ ] Added e2e tests

- [ ] Did you follow our [Security Best Practices](https://oktawiki.atlassian.net/wiki/display/eng/Security+Best+practices)?

- Did you verify the change by running downstream monolith artifacts? (YES | NO | UNSURE)

### Screenshot/Video:

### Reviewers:

### Issue:

- [OKTA-521071](https://oktainc.atlassian.net/browse/OKTA-521071)

2022-08-04 13:32 UTC, jaredperreault-okta approved these changes

2022-08-04 13:49 UTC, shuowu-okta requested changes
Seems like we don't need these changes for weekly release

2022-08-04 16:16 UTC, jaredperreault-okta approved these changes

2022-08-04 16:16 UTC, aarongranick-okta approved these changes

2022-08-04 16:18 UTC, shuowu-okta approved these changes

2022-08-05 16:42 UTC, lesterchoi-okta commented
Closing. Included in https://github.com/okta/okta-signin-widget/pull/2672

2022-08-05 16:42 UTC, closed without merging