Fix CSP style-src violation in Util.js
okta/okta-signin-widget pull request #2904
Opened 2022-11-04 14:48 UTC by kamaldeepcheema-okta

## Description:

- Fixing the CSP style-src violation in Util.js as per the guidelines here: https://oktawiki.atlassian.net/wiki/spaces/eng/pages/2703983302/Identifying+Fixing+style-src+based+CSP+vulns#2.-style-in-attribute

## PR Checklist

- [ ] Have you verified the basic functionality for this change?
- [ ] Did you add tests, as appropriate, following our [Automated Test guidelines](https://oktawiki.atlassian.net/wiki/spaces/eng/pages/2676497890/Automated+Testing+in+the+Signin+Widget)?
- [ ] Did you follow our [Security Best Practices](https://oktawiki.atlassian.net/wiki/display/eng/Security+Best+practices)?
- [ ] Did you verify the change by running [downstream monolith artifact](https://oktawiki.atlassian.net/wiki/spaces/eng/pages/102897979/Sign-in+Widget+Development#Sign-inWidgetDevelopment-Instructionstocreateandrunthedownstreamartifact(d16t))? (Provide link to build below)
- [ ] Does this PR include noticeable changes to the UI? (If yes, attach screenshots/video below)

### Issue:

- [OKTA-548150](https://oktainc.atlassian.net/browse/OKTA-548150)

### Reviewers:

### Screenshot/Video:

### Downstream Monolith Build:

2022-11-04 14:49 UTC, kamaldeepcheema-okta commented on test/testcafe/spec/IdentifyWithThirdPartyIdps_spec.js
> +  await t.wait(100);
I noticed a lot of Bacon flakiness with this test, and uncommenting this seems to make it stable.

2022-11-04 16:48 UTC, aarongranick-okta requested changes
Can you add a test to assert the fix and also protect against regressions?

CSP headers are added to the test app here:
https://github.com/okta/okta-signin-widget/blob/42dc0dc9f843284b7ab1c7cfe73f098e0b5956da/test/app/webpack.config.js#L52
(for E2E tests)

and to the widget playground here:
https://github.com/okta/okta-signin-widget/blob/master/webpack.playground.config.js#L37
(For testcafe)

The current approach is to enforce CSP across all tests. Then a "negative" test is added to be sure that we are not getting false positives: https://github.com/okta/okta-signin-widget/blob/42dc0dc9f843284b7ab1c7cfe73f098e0b5956da/test/e2e/features/basic.feature#L22 This is currently only testing with eval:

https://github.com/okta/okta-signin-widget/blob/2d0e19a72c39d666d7c5b76ed984f0457dd7f5ff/test/app/src/TestApp.ts#L292 

We should test that both script-src and style-src are being enforced as expected.

2022-11-04 21:26 UTC, kamaldeepcheema-okta commented on test/testcafe/spec/IdentifyWithThirdPartyIdps_spec.js
> +  await t.wait(100);
Yeah I did try to debug this quite a bit locally and the first thing I tried was to wait for the form render with the social auth buttons but that didn't seem to help. Tbh, I wasn't quite sure why that didn't work and a specific wait for 100ms did. But I can try to investigate some more.

2022-12-09 19:35 UTC, sherizada-okta commented
merged into this PR https://github.com/okta/okta-signin-widget/pull/2925

2022-12-09 19:35 UTC, closed without merging