Use core-js/stable in polyfill to fix legacy browser support issue
okta/okta-signin-widget pull request #2986
Opened 2022-12-15 14:29 UTC by shuowu-okta

## Description:

With this change`okta-sign-in.min.js` and `okta-sign-in.polyfill.min.js` will have around 80k size increase.

Bundles size (before change):
```
 12K    okta-plugin-a11y.js
 24K    okta-plugin-a11y.js.map
2.4M    okta-sign-in.classic.js
3.5M    okta-sign-in.classic.js.map
1.1M    okta-sign-in.classic.min.js
3.2M    okta-sign-in.classic.min.js.map
3.2M    okta-sign-in.js
4.5M    okta-sign-in.js.map
1.6M    okta-sign-in.min.js
4.7M    okta-sign-in.min.js.map
1.6M    okta-sign-in.no-polyfill.min.js
4.1M    okta-sign-in.no-polyfill.min.js.map
2.4M    okta-sign-in.oie.js
3.5M    okta-sign-in.oie.js.map
1.3M    okta-sign-in.oie.min.js
3.2M    okta-sign-in.oie.min.js.map
476K    okta-sign-in.polyfill.js
404K    okta-sign-in.polyfill.js.map
100K    okta-sign-in.polyfill.min.js
492K    okta-sign-in.polyfill.min.js.map
```

Bundles size (after change)
```
 12K    okta-plugin-a11y.js
 24K    okta-plugin-a11y.js.map
2.4M    okta-sign-in.classic.js
3.5M    okta-sign-in.classic.js.map
1.1M    okta-sign-in.classic.min.js
3.2M    okta-sign-in.classic.min.js.map
3.2M    okta-sign-in.js
4.5M    okta-sign-in.js.map
1.7M    okta-sign-in.min.js
5.0M    okta-sign-in.min.js.map
1.6M    okta-sign-in.no-polyfill.min.js
4.1M    okta-sign-in.no-polyfill.min.js.map
2.4M    okta-sign-in.oie.js
3.5M    okta-sign-in.oie.js.map
1.3M    okta-sign-in.oie.min.js
3.2M    okta-sign-in.oie.min.js.map
880K    okta-sign-in.polyfill.js
748K    okta-sign-in.polyfill.js.map
180K    okta-sign-in.polyfill.min.js
896K    okta-sign-in.polyfill.min.js.map
```

## PR Checklist

- [ ] Have you verified the basic functionality for this change?
- [ ] Did you add tests, as appropriate, following our [Automated Test guidelines](https://oktawiki.atlassian.net/wiki/spaces/eng/pages/2676497890/Automated+Testing+in+the+Signin+Widget)?
- [ ] Did you follow our [Security Best Practices](https://oktawiki.atlassian.net/wiki/display/eng/Security+Best+practices)?
- [ ] Did you verify the change by running [downstream monolith artifact](https://oktawiki.atlassian.net/wiki/spaces/eng/pages/102897979/Sign-in+Widget+Development#Sign-inWidgetDevelopment-Instructionstocreateandrunthedownstreamartifact(d16t))? (Provide link to build below)
- [ ] Does this PR include noticeable changes to the UI? (If yes, attach screenshots/video below)

### Issue:

- [OKTA-559547](https://oktainc.atlassian.net/browse/OKTA-559547)

### Reviewers:

### Screenshot/Video:

### Downstream Monolith Build:

2022-12-15 19:29 UTC, lesterchoi-okta requested changes

2022-12-15 19:29 UTC, lesterchoi-okta commented on .bacon.yml
> +      criteria: OPTIONAL
revert?

2022-12-15 20:04 UTC, aarongranick-okta approved these changes

2022-12-15 21:05 UTC, shuowu-okta commented on .bacon.yml
> +      criteria: OPTIONAL
resolved

2022-12-15 21:14 UTC, lesterchoi-okta approved these changes

2022-12-15 22:14 UTC, merged

2022-12-18 00:59 UTC, Youknow769 requested changes
Not sure what happen