grab stateToken from window.oktaData for Okta-hosted custom SIW
okta/okta-signin-widget pull request #2997
Opened 2022-12-20 01:40 UTC by sherizada-okta

## Description:
use stateToken from oktaData if available (only set on window for custom Okta hosted SIW) to prevent customers who override config options and lose the stateToken set in config

prevents this scenario
1. Edit code in Sign in page code editor 
2. Set `config` to a new object without carrying over stateToken ` config = { ...myNewOptions } `
3. Sign into some app with a custom domain set
  a. on OIE, user will not be able to log in
  b. on Classic, user will not be redirected to correct app

## PR Checklist

- [ ] Have you verified the basic functionality for this change?
- [ ] Did you add tests, as appropriate, following our [Automated Test guidelines](https://oktawiki.atlassian.net/wiki/spaces/eng/pages/2676497890/Automated+Testing+in+the+Signin+Widget)?
- [ ] Did you follow our [Security Best Practices](https://oktawiki.atlassian.net/wiki/display/eng/Security+Best+practices)?
- [ ] Did you verify the change by running [downstream monolith artifact](https://oktawiki.atlassian.net/wiki/spaces/eng/pages/102897979/Sign-in+Widget+Development#Sign-inWidgetDevelopment-Instructionstocreateandrunthedownstreamartifact(d16t))? (Provide link to build below)
- [ ] Does this PR include noticeable changes to the UI? (If yes, attach screenshots/video below)

### Issue:

- [OKTA-561119](https://oktainc.atlassian.net/browse/OKTA-561119)

### Reviewers:

### Screenshot/Video:

### Downstream Monolith Build:

2022-12-20 18:51 UTC, sherizada-okta commented on src/widget/OktaSignIn.ts
> +      this.options.stateToken = window?.oktaData?.signIn?.stateToken;
I am also contemplating setting the stateToken in the Admin sign in page code editor:
```
config.stateToken = oktaData.signIn.stateToken; // required
```

2022-12-21 19:51 UTC, lesterchoi-okta commented on src/widget/OktaSignIn.ts
> +      this.options.stateToken = window?.oktaData?.signIn?.stateToken;
add check that `stateToken` isn't already set

2022-12-21 19:51 UTC, lesterchoi-okta commented on src/widget/OktaSignIn.ts
> +      this.options.stateToken = window?.oktaData?.signIn?.stateToken;
nit: `window.oktaData.signIn.stateToken`

2022-12-22 14:45 UTC, lesterchoi-okta requested changes

2022-12-22 21:01 UTC, sherizada-okta commented on src/models/Settings.ts
> +    oktaData: OktaData;
yes, done.

2023-01-04 19:08 UTC, lesterchoi-okta approved these changes
:shipit:

2023-01-04 19:51 UTC, merged